version: "3.9"
services:
  database:
    container_name: rust-database
    image: postgres:15-alpine
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - rust-bridge
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 30s
      retries: 3


networks:
  rust-bridge:
    driver: bridge
